# START PROBLEM SET 10
print('Problem set 10 \n')

# SETUP

import requests, csv, json

ENDPOINT = 'https://swapi.py4e.com/api'

#END SETUP

# Problem 01
def get_swapi_resource(resource, params=None, timeout=20):
    """
    This function initiates an HTTP GET request to the SWAPI service in order to return a
    representation of a resource. <params> is not included in the request if no params is passed to this
    function during the function call. Once a response is received, it is converted to a python dict.

    Parameters:
        resource (str): a url that specifies the resource.
        params (dict): optional dictionary of querystring arguments. The default value is None.
        timeout (int): timeout value in seconds. The default value is 20.

    Returns:
        dict: dictionary representation of the decoded JSON.
    """
    return requests.get(resource, params, timeout=timeout).json()

# Problem 02
def convert_resource_to_obj(resource_dict, obj_class):
    """
    This function converts a resource dictionary to an object of a given class. The
    <resource_dict> can be a dictionary returned by <get_swapi_resource> or by <read_json>.
    It looks for the keys in the <resource_dict> for a match in the object_class.properties.
    It then creates an object of <obj_class> using the values from the <resource_dict> whose keys
    had a match in the object_class.properties and returns the object.

    Parameters:
        resource (str): a url that specifies the resource.
        obj_class (cls): a class that initiates the instance

    Returns:
        instance (obj): an instance generated by <obj_class>.
    """
    obj_properties = []

    for key, value in resource_dict.items():
        if key in obj_class.properties:
            obj_properties.append(value)


    # Do not change the following return statement. The "*" operator is used to unpack the
    # items from the 'obj_properties' list to arguments for instansiating an object class.

    # TODO: Uncomment the following when ready!
    return obj_class(*obj_properties)

# Problem 03
def read_json(filepath):
    """
    This function reads in a JSON file and converts it into a dictionary and returns it.

    Parameters:
        filepath(str): The location and filename of the JSON file

    Returns:
        data(dict): A parsed dictionary of resources.
    """
    with open(filepath, 'r', encoding='utf-8') as file_obj:
        return json.load(file_obj)

# Problem 04
def write_json(filepath, data):
    """
    This function dumps the JSON object in the dictionary <data> into a file on
    <filepath>.

    Parameters:
        filepath(str): The location and filename of the file to store the JSON
        data(dict): The dictionary that contains the JSON representation of the objects.

    Returns:
        None
    """
    with open(filepath, 'w', encoding='utf-8') as file_obj:
        json.dump(data, file_obj, ensure_ascii=False, indent=2)


# Problem 05
class Film:
    """"
    Representation of a Film.

    Attributes:
        title(str): title of the film
        episode_id(str): the episode number of the film
        url(str): the url of the film
        properties(tuple): A tuple of all other attributes of the class
    """
    properties = ("title", "episode_id", "url")
    def __init__(self, title, episode_id, url): # TODO: Complete the parameter list
        """
        The constructor of the <Film>. It takes in the given parameters
        and assigns them to the attributes (instance variables) of the class.

        Parameters:
            title(str): title of the film
            episode_id(str): the episode number of the film
            url(str): the url of the film

        Returns:
            None
        """
        self.title = title
        self.episode_id = episode_id
        self.url = url
        #self.properties = properties

    def __str__(self):
        """
        This method provides a readable string representation of the object.

        Parameters:
            None

        Returns:
            An f-string with the syntax: 'The film "<title>" is  episode <episode_id>.'
        """
        return f'The film "{self.title}" is episode {self.episode_id}.'

    def jsonable(self):
        """
        Return a JSON-friendly representation of the object.
        The key should be the name of instance variable and value should be the corresponding value.
        For example, self.title should be converted in this way:
        {"title": self.title}

        Parameters:
            None

        Returns:
            dict: dictionary of the object's instance variables
        """
        # interesting_dict = {
        #     'title' : self.title,
        #     'episode_id' : self.episode_id,
        #     'url' : self.url
        # }

        return {
            "title" : self.title,
            "episode_id" : self.episode_id,
            "url" : self.url
        }

# Problem 06
class Person:
    """
    Representation of a Person

    Attributes:
        name(str): Name of the person
        hair_color(str): Color of hair
        skin_color(str): Color of skin
        eye_color(str): Color of eye
        gender(str): Gender
        films(list): List of films the person appears in
        url(str): URL to the person
        properties(str): A tuple of all other attributes of the class
    """
    properties = ("name", "hair_color", "skin_color", "eye_color", "gender", "films", "url")

    def __init__(self, name, hair_color, skin_color, eye_color, gender, films, url): # TODO: Complete the parameter list
        """
        The constructor of the <Person>. It takes in the given parameters
        and assigns them to the attributes (instance variables) of the class.

        Parameters:
            name(str): Name of the person
            hair_color(str): Color of hair
            skin_color(str): Color of skin
            eye_color(str): Color of eye
            gender(str): Gender
            films(list): List of films the person appears in
            url(str): URL to the person

        Returns:
            None
        """
        self.name = name
        self.hair_color = hair_color
        self.skin_color = skin_color
        self.eye_color = eye_color
        self.gender = gender
        self.films = films
        self.url = url

    def __str__(self):
        """
        This method provides a readable string representation of the object.

        Parameters:
            None

        Returns:
            An f-string with the syntax: "<name> has <hair_color> hair and <eye_color> eyes."
        """
        return f"{self.name} has {self.hair_color} hair and {self.eye_color} eyes."

    def update_films(self):
        """
        This method takes the list of URLS and creates new objects of <Film> class for each film class
        and replaces the <films> instance variable with a list of Film objects. It makes use of the
        <convert_resource_to_obj()> function and the <get_swapi_resource()>.

        Parameters:
            None

        Retruns:
            None
        """
        list_of_films = []
        for item in self.films:
            property_dict = get_swapi_resource(item)
            film_obj = convert_resource_to_obj(property_dict, Film)
            list_of_films.append(film_obj)
        self.films = list_of_films

    def jsonable(self):
        """
        Return a JSON-friendly representation of the object.
        The key should be the name of instance variable and value should be the corresponding value.
        For example, self.name should be converted in this way:
        {"name": self.name}

        Parameters:
            None
        Returns:S
            dict: dictionary of the object's instance variables
        """
        return {
            "name": self.name,
            "hair_color": self.hair_color,
            "skin_color": self.skin_color,
            "eye_color": self.eye_color,
            "gender": self.gender,
            "films": [self.films],
            "url": self.url
        }

def main():
    """
    Program entry point. Handles program workflow.

    Parameters:
        None

    Returns:
        people_info(dict)
        people_objects(dict)
        rey_instance(str)
        write_dict(dict)
    """
    pass # TODO: Implement
    # Problem 7.1
    people_info = read_json('people.json')
    people_objects = {}

    # Problem 7.2
    # rey = get_swapi_resource(ENDPOINT+'/people', params={'search' : 'Rey'})
    # finn = get_swapi_resource(ENDPOINT+'/people', params={'search' : 'Finn'})
    # c_3po = get_swapi_resource(ENDPOINT+'/people', params={'search' : 'C-3PO'})
    # chewbacca = get_swapi_resource(ENDPOINT+'/people', params={'search' : 'Chewbacca'})

    for key in people_info.keys():
        data = get_swapi_resource(ENDPOINT+'/people', {'search' : key})['results'][0]
        person = Person(data['name'], data['hair_color'], data['skin_color'], data['eye_color'], data['gender'], data['films'], data['url'])
        person.update_films()
        people_objects[person.name] = person
    rey_instance = people_objects['Rey'].__str__()

    # Problem 7.3
    #for key in people_info.keys():
        #data = get_swapi_resource(ENDPOINT+'/people', params={'search' : key})

    # Problem 7.4
    write_dict = {}
    json_films = []
    for value in people_objects.values():
        for film in value.films:
            json_films.append(film.jsonable())
        value.films = json_films

    for key, val in people_objects.items():
        write_dict[key] = val.jsonable()
    write_json('updated_people.json', write_dict)

    # Don't forget to return variables
    # If you want to test your code before you finish all the PS,
    # you can assign None to those return variables
    return people_info, people_objects, rey_instance, people_info

#Do not delete the lines below.
if __name__ == '__main__':
    main()